spring.datasource.url=jdbc:mysql://localhost:3306/visitor_tracking
spring.datasource.username=root
spring.datasource.password=Selva@030

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=visitorroute@gmail.com
spring.mail.password=vtibkrjlxgdbfljy

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

twilio.sid=YOUR_SID
twilio.token=YOUR_TOKEN
twilio.number=YOUR_PHONE

# CORS Configuration
app.cors.allowed-origins=http://localhost:4200